# Embeds a compiled SPIR-V file into a C header as a byte array.
# Usage: cmake -DINPUT=shader.spv -DOUTPUT=shader.h -DVARNAME=shader_name -P embed_shader.cmake

file(READ "${INPUT}" content HEX)
string(REGEX MATCHALL "[0-9a-fA-F][0-9a-fA-F]" byte_chars "${content}")
string(REPLACE ";" ",0x" bytes "${byte_chars}")

file(WRITE "${OUTPUT}"
"// Generated by embed_shader.cmake — do not edit.
#pragma once

namespace synapse {
inline constexpr unsigned char ${VARNAME}_data[] = { 0x${bytes} };
inline constexpr unsigned int ${VARNAME}_size = sizeof(${VARNAME}_data);
} // namespace synapse
")
